/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MaombiBinafsiRouteImport } from './routes/maombi-binafsi'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SikuDayRouteImport } from './routes/siku.$day'

const MaombiBinafsiRoute = MaombiBinafsiRouteImport.update({
  id: '/maombi-binafsi',
  path: '/maombi-binafsi',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SikuDayRoute = SikuDayRouteImport.update({
  id: '/siku/$day',
  path: '/siku/$day',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/maombi-binafsi': typeof MaombiBinafsiRoute
  '/siku/$day': typeof SikuDayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/maombi-binafsi': typeof MaombiBinafsiRoute
  '/siku/$day': typeof SikuDayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/maombi-binafsi': typeof MaombiBinafsiRoute
  '/siku/$day': typeof SikuDayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/maombi-binafsi' | '/siku/$day'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/maombi-binafsi' | '/siku/$day'
  id: '__root__' | '/' | '/maombi-binafsi' | '/siku/$day'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MaombiBinafsiRoute: typeof MaombiBinafsiRoute
  SikuDayRoute: typeof SikuDayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/maombi-binafsi': {
      id: '/maombi-binafsi'
      path: '/maombi-binafsi'
      fullPath: '/maombi-binafsi'
      preLoaderRoute: typeof MaombiBinafsiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/siku/$day': {
      id: '/siku/$day'
      path: '/siku/$day'
      fullPath: '/siku/$day'
      preLoaderRoute: typeof SikuDayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MaombiBinafsiRoute: MaombiBinafsiRoute,
  SikuDayRoute: SikuDayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
